### ISSUE TITLE
커버 532곡 전부 플리에 넣었을 때 목록 전환 렉 걸림

### ISSUE THREAD

**Issue by koreakane** [mskim9967/isedol-cover-streaming#1]
https://user-images.githubusercontent.com/38726323/156015292-eccba466-636d-4bd1-b11d-58d85fe4f836.mov

플리에 200곡 정도부터 렉이 미세하게 걸리며, 400곡 이후로 렉이 눈에 띄게 걸립니다.

https://github.com/mskim9967/isedol-cover-streaming/blob/1d55a982627146451555f68e901e2f601759efe7/frontend/src/component/MusicPlay.js#L337

이 부분에서 display가 isPlaylistActive state 상태에 따라 normal과 none 전환이 일어나면서 일어나는 렉으로 보입니다.

display 스위치를 만드는 것보다는 postion relative-absolute를 통해 프로필 사진을 absolute로 띄워놓고 absolute에 따른 프로필 사진과 플레이리스트 위치 조정 후 display 부분에 isPlayActive 스위치를 제거하면 해결됩니다.

https://github.com/mskim9967/isedol-cover-streaming/blob/1d55a982627146451555f68e901e2f601759efe7/frontend/src/component/MusicPlay.js#L167
이 부분에 position relative를 달아놓고, 

https://github.com/mskim9967/isedol-cover-streaming/blob/1d55a982627146451555f68e901e2f601759efe7/frontend/src/component/MusicPlayer.js#L174
이 부분에 position absolute를 달고 위치 조정을 추가로 하신 뒤 

https://github.com/mskim9967/isedol-cover-streaming/blob/1d55a982627146451555f68e901e2f601759efe7/frontend/src/component/MusicPlay.js#L337
이 부분에서 display 부분에 isPlaylistActive 스위치를 제거하시고 추가로 위치 조정을 하면 해결됩니다.

https://user-images.githubusercontent.com/38726323/156020292-4801221d-a19d-45ff-b945-83365e592c1f.mov

**Comment by mskim9967** [comment]
- position 적절히 조절하여 display none 속성 제거 완료 
- MusicCardInPlaylist 컴포넌트 안의 Button(Nextui) 렌더링에서 추가적인 속도 저하 발견, Button 제거 완료

스파게티 코드 분석해주시느라 정말 고생하셨고 감사합니다🙏

1d68d878fc6c76b71d3f3df08f6346bcb89d09e2
