### ISSUE TITLE
플레이리스트 좌우 스크롤이 데스크톱 환경에서 적용이 안됨

### ISSUE THREAD

**Issue by koreakane** [mskim9967/isedol-cover-streaming#2]
아이돌별 추천, 나의 플레이리스트 둘 다 데스크톱 환경에서 좌우로 스와이핑이나 스크롤이 안됩니다.

**Comment by mskim9967** [comment]
desktop 환경에서 horizontal scrollbar 활성화되도록 css 수정 완료

제보 늘 감사합니다🙏

96eff390bc5a5d6ab8917dbb5c4a9874106728d2
